name: cleaning
on: push
permissions:
  contents: write
jobs:
  pipeline:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: clean
        run: |
          git config --global user.email "njkznu@gmail.com"
          git config --global user.name "kuzanatoliy"
          branchList=`git branch --remotes | grep -v "origin/HEAD -> *"`
          for branch in $branchList
          do
            name=`echo $branch | cut -d "/" -f 2`
            echo $branch
            echo $name
            if [ $name != master -a $name != develop -a $name != gh-pages ]
            then
              echo $name
              # git push origin -d $name
            fi
          done
