name: e2e
on:
  workflow_dispatch:
    inputs:
      testSuit:
        description: Chose test suit to run
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - general
          - flexbox adventure
          - grid attack
          - NCP panic
jobs:
  pipeline:
    runs-on: ubuntu-24.04
    environment: e2e
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: configure
        run: |
          echo "{\"email_password\":\"${{ secrets.EMAIL_PASSWORD }}\",\"login\":\"${{vars.LOGIN}}\",\"email_login\":\"${{vars.EMAIL_LOGIN}}\"}" > cypress.env.json
      - name: install dependencies
        run: npm install
      - name: run generall e2e tests
        if: ${{ inputs.testSuit == 'all' || inputs.testSuit == 'general' }}
        run: npm run cy:run -- --spec "cypress/e2e/codingfantasy.cy.ts"
      - name: run flexbox adventure e2e tests
        if: ${{ inputs.testSuit == 'all' || inputs.testSuit == 'flexbox adventure' }}
        run: npm run cy:run -- --spec "cypress/e2e/flexboxadventure.cy.ts"
      - name: run grid attack e2e tests
        if: ${{ inputs.testSuit == 'all' || inputs.testSuit == 'grid attack' }}
        run: npm run cy:run -- --spec "cypress/e2e/gridattack.cy.ts"
      - name: run ncp panic e2e tests
        if: ${{ inputs.testSuit == 'all' || inputs.testSuit == 'NCP panic' }}
        run: npm run cy:run -- --spec "cypress/e2e/mcp.cy.ts"
