name: e2e
on: push
jobs:
  pipeline:
    runs-on: ubuntu-latest
    environment: e2e
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: configure
        run: |
          echo "{\"email_password\": \"${{ secrets.EMAIL_PASSWORD }}\",\"login\":"\${{vars.LOGIN}}\",\"email_login\":\"${{vars.EMAIL_LOGIN}}\"}" >> cypress.env.json
      - name: install dependencies
        run: npm install
      - name: e2e testing
        run: npm run cy:run
